export const COUNTRY_NAMES: string[] = [
  'Aldoria',
  'Bergund',
  'Caldria',
  'Estenmark',
  'Lotharing',
  'Ravenna',
  'Valdric',
  'Westmere',
  'Dornheim',
  'Ferrath',
  'Greymark',
  'Hartfeld',
  'Ironwall',
  'Kelvara',
  'Lundbeck',
  'Morvaine',
  'Norwick',
  'Ostmark',
  'Pelstein',
  'Quelmar',
]

export const HOUSE_NAMES: string[] = [
  'House Arden',
  'House Falken',
  'House Montclair',
  'House Ravensburg',
  'House Valmont',
  'House Eisenwald',
  'House Hohenfels',
  'House Bellacourt',
  'House Crestfeld',
  'House Dunmore',
  'House Elderwick',
  'House Frostgate',
  'House Grimwald',
  'House Hartstone',
  'House Ironmoor',
  'House Kendrick',
  'House Larkspur',
  'House Merriwick',
  'House Nighthollow',
  'House Oswick',
  'House Aldercrest',
  'House Aldenhof',
  'House Amberley',
  'House Ashbourne',
  'House Asterfeld',
  'House Aubermont',
  'House Blackwell',
  'House Blankenburg',
  'House Briarford',
  'House Brightmere',
  'House Brockenhurst',
  'House Carroway',
  'House Castellane',
  'House Clairvaux',
  'House Coldwater',
  'House Corvin',
  'House Dalenberg',
  'House Dawnhurst',
  'House Deveraux',
  'House Dornwald',
  'House Drakenhof',
  'House Duskendale',
  'House Eberstein',
  'House Eldermere',
  'House Emberfall',
  'House Everhart',
  'House Fairbourne',
  'House Falkenhayn',
  'House Felden',
  'House Fenwick',
  'House Fernbrook',
  'House Fierstahl',
  'House Greyford',
  'House Greymont',
  'House Grunwald',
  'House Hagenau',
  'House Harrowmont',
  'House Haverford',
  'House Highmere',
  'House Hohenbruck',
  'House Holtzmann',
  'House Ironhart',
  'House Jorvik',
  'House Kaltstein',
  'House Kingsford',
  'House Kirchberg',
  'House Langenfeld',
  'House Lindenau',
  'House Lowenfels',
  'House Marburg',
  'House Marlowe',
  'House Morncrest',
  'House Nachtwald',
  'House Northwick',
  'House Oakenshield',
  'House Osterfeld',
  'House Ravenscar',
  'House Redwyne',
  'House Reichenau',
  'House Reinwald',
  'House Rosenthal',
  'House Rothenberg',
  'House Saalfeld',
  'House Saint-Aubin',
  'House Schattenburg',
  'House Seabrook',
  'House Silvermere',
  'House Sommerfeld',
  'House Stagbourne',
  'House Steinbruck',
  'House Sternfels',
  'House Stonehaven',
  'House Stormwald',
  'House Talbot',
  'House Thornfield',
  'House Thornwick',
  'House Tiefenbach',
  'House Valeworth',
  'House Varenne',
  'House Verdun',
  'House Veyrac',
  'House Wainwright',
  'House Waldstein',
  'House Warwick',
  'House Wendelhof',
  'House Westermark',
  'House Whitecliff',
  'House Winterbourne',
  'House Wolfenbach',
  'House Wolfhart',
  'House Wyvernfall',
  'House Ysenburg',
  'House Zehringen',
]

export const MALE_NAMES: string[] = [
  'Adalbert',
  'Alaric',
  'Baldwin',
  'Conrad',
  'Edmund',
  'Frederick',
  'Geoffrey',
  'Hugh',
  'Leopold',
  'Matthias',
  'Otto',
  'Raymond',
  'Roland',
  'Theobald',
  'William',
  'Heinrich',
  'Sigmund',
  'Gottfried',
  'Hartmann',
  'Dietrich',
  'Albrecht',
  'Berthold',
  'Clemens',
  'Ekkehard',
  'Gerhard',
  'Hildebrand',
  'Johannes',
  'Klaus',
  'Lorenz',
  'Arnulf',
  'Aldric',
  'Anselm',
  'Archibald',
  'Armand',
  'Arnold',
  'Benedict',
  'Bernard',
  'Bruno',
  'Caspar',
  'Christian',
  'Diederik',
  'Eberhard',
  'Egon',
  'Elias',
  'Emmerich',
  'Erich',
  'Ernst',
  'Everard',
  'Ferdinand',
  'Florian',
  'Franz',
  'Gebhard',
  'Gilbert',
  'Gregor',
  'Gunther',
  'Gustav',
  'Hadrian',
  'Hermann',
  'Hubert',
  'Ivo',
  'Jakob',
  'Jasper',
  'Karl',
  'Konrad',
  'Lambert',
  'Lothar',
  'Ludolf',
  'Ludwig',
  'Magnus',
  'Manfred',
  'Markward',
  'Moritz',
  'Nikolaus',
  'Oswald',
  'Otfried',
  'Philipp',
  'Rainer',
  'Reinhard',
  'Roderick',
  'Rudolf',
  'Rupert',
  'Sebastian',
  'Siegfried',
  'Stefan',
  'Ulrich',
  'Urban',
  'Victor',
  'Volker',
  'Waldemar',
  'Walther',
  'Werner',
  'Wenzel',
  'Wilhelm',
  'Wolfram',
  'Wolfgang',
  'Ademar',
  'Amaury',
  'Anatole',
  'Aubrey',
  'Berenger',
  'Charles',
  'Dorian',
  'Eustace',
  'Fulk',
  'Gaston',
  'Gerald',
  'Gervase',
  'Godfrey',
  'Guy',
  'Henri',
  'Humbert',
  'Joscelin',
  'Lionel',
  'Odo',
  'Percival',
  'Reginald',
  'Robert',
  'Roger',
  'Simon',
  'Thierry',
  'Tristan',
  'Valentin',
  'Vincent',
  'Walter',
  'Yves',
]

export const FEMALE_NAMES: string[] = [
  'Adelheid',
  'Agnes',
  'Beatrix',
  'Bertha',
  'Clara',
  'Dorothea',
  'Elisabeth',
  'Gisela',
  'Hedwig',
  'Hildegard',
  'Irmgard',
  'Johanna',
  'Katharina',
  'Kunigunde',
  'Liutgard',
  'Mathilde',
  'Mechthild',
  'Richardis',
  'Sophia',
  'Ursula',
  'Walburga',
  'Wilhemina',
  'Adelinde',
  'Berta',
  'Crescentia',
  'Ermengard',
  'Felizitas',
  'Gertrude',
  'Hadwig',
  'Isolde',
  'Adela',
  'Adelina',
  'Alberada',
  'Alix',
  'Amalia',
  'Anna',
  'Anneliese',
  'Aveline',
  'Barbara',
  'Benedikta',
  'Blanche',
  'Brigitta',
  'Cecilia',
  'Christina',
  'Clarissa',
  'Constantia',
  'Diemut',
  'Eleanor',
  'Elfrida',
  'Elsbeth',
  'Emilia',
  'Emma',
  'Erika',
  'Ermentrude',
  'Euphemia',
  'Eva',
  'Florentina',
  'Franziska',
  'Frederika',
  'Genovefa',
  'Griselda',
  'Gudrun',
  'Helena',
  'Henrietta',
  'Ida',
  'Ilse',
  'Imagina',
  'Irmela',
  'Judith',
  'Juliana',
  'Justina',
  'Klara',
  'Leoba',
  'Leonor',
  'Luitgard',
  'Magdalena',
  'Margarete',
  'Marguerite',
  'Maria',
  'Marianne',
  'Melisende',
  'Odilia',
  'Ottilie',
  'Philippa',
  'Regina',
  'Rosamund',
  'Roswitha',
  'Sabina',
  'Sibylle',
  'Thekla',
  'Theodora',
  'Theresia',
  'Verena',
  'Waltrud',
  'Wendelina',
  'Wilhelmina',
  'Winifred',
  'Ysabel',
  'Adelais',
  'Agneta',
  'Alienor',
  'Amice',
  'Avice',
  'Clemence',
  'Elaine',
  'Eloise',
  'Emeline',
  'Fleur',
  'Gundred',
  'Heloise',
  'Isabella',
  'Jacqueline',
  'Jeanne',
  'Joan',
  'Lucia',
  'Mabel',
  'Matilda',
  'Millicent',
  'Petronilla',
  'Sybil',
  'Yolande',
]

export const PROVINCE_NAMES: string[] = [
  'Ashford',
  'Blackmere',
  'Carrenwood',
  'Dawnfield',
  'Elderstone',
  'Fengate',
  'Greyhollow',
  'Harwick',
  'Ironbridge',
  'Jadenvale',
  'Keswick',
  'Larchford',
  'Millhaven',
  'Northmarch',
  'Oakenveil',
  'Pinehurst',
  'Queensmere',
  'Ravenwood',
  'Stonehaven',
  'Thornbury',
  'Underhill',
  'Valewood',
  'Westbrook',
  'Ximoor',
  'Yewdale',
  'Zephyrport',
  'Ambergate',
  'Bramblewood',
  'Coldwater',
  'Dunstead',
  'Elmcross',
  'Foxmoor',
  'Gildenford',
  'Highcliff',
  'Ivywood',
  'Jaspermere',
  'Knotwood',
  'Lambourne',
  'Misthollow',
  'Nettlebrook',
  'Alderbrook',
  'Alderford',
  'Aldermere',
  'Applewick',
  'Ardenfield',
  'Ashbourne',
  'Ashenmoor',
  'Barrowfield',
  'Bellwater',
  'Birchcross',
  'Blackbrook',
  'Blackfen',
  'Blackridge',
  'Bleakmoor',
  'Blueford',
  'Briarcliff',
  'Brightwater',
  'Brookhaven',
  'Brookmere',
  'Burrowdale',
  'Candleford',
  'Castleford',
  'Cedarwick',
  'Cliffmere',
  'Cloudbury',
  'Copperfield',
  'Crowhurst',
  'Crowmere',
  'Darkwater',
  'Deephollow',
  'Deepwood',
  'Deerwick',
  'Dewhurst',
  'Dragonford',
  'Dunbridge',
  'Dunfield',
  'Dunford',
  'Eastmere',
  'Eastwick',
  'Ebonford',
  'Ebonmoor',
  'Elmhurst',
  'Emberwick',
  'Fairford',
  'Falconridge',
  'Farbrook',
  'Farrowdale',
  'Fenbridge',
  'Fennwick',
  'Frostford',
  'Frostmere',
  'Glenhaven',
  'Goldbrook',
  'Goldmere',
  'Gravelford',
  'Greenbarrow',
  'Greenhollow',
  'Greenmere',
  'Greybridge',
  'Greyford',
  'Grimford',
  'Hawkfield',
  'Hazelbury',
  'Hazelwick',
  'Heatherford',
  'Highbrook',
  'Highfield',
  'Highmarch',
  'Hillford',
  'Hollowbrook',
  'Honeywick',
  'Hornvale',
  'Ironford',
  'Ironhollow',
  'Kingsbridge',
  'Kingsfield',
  'Kingshaven',
  'Kingswood',
  'Lakeford',
  'Larkfield',
  'Lindenbrook',
  'Littleford',
  'Longbridge',
  'Longmere',
  'Lowenford',
  'Maplehurst',
  'Meadowbrook',
  'Mereford',
  'Merrydale',
  'Mistford',
  'Moonbrook',
  'Mossford',
  'Mossvale',
  'Newwick',
  'Northbrook',
  'Oakbridge',
  'Oakendale',
  'Oakford',
  'Oldmere',
  'Oldwick',
  'Otterford',
  'Oxbridge',
  'Palehurst',
  'Pineford',
  'Ravenbridge',
  'Ravenshire',
  'Redbrook',
  'Redcliff',
  'Redford',
  'Reedmere',
  'Riverbend',
  'Rivermarch',
  'Roseford',
  'Rushwick',
  'Saltmere',
  'Seabrook',
  'Seacliff',
  'Shadowfen',
  'Silverbrook',
  'Silverford',
  'Southwick',
  'Springmere',
  'Stagford',
  'Stagwick',
  'Starfall',
  'Stillwater',
  'Stormcliff',
  'Stormford',
  'Sunfield',
  'Swanford',
  'Thistleford',
  'Thornfield',
  'Thornford',
  'Threeford',
  'Timberwick',
  'Tumbledown',
  'Valehaven',
  'Westerford',
  'Whitebrook',
  'Whitecliff',
  'Whiteford',
  'Willowdale',
  'Willowmere',
  'Windermere',
  'Winterfield',
  'Wintermere',
  'Wolfbridge',
  'Wolfden',
  'Wolfmere',
  'Woodhurst',
  'Wyverncliff',
  'Wyvernford',
  'Yellowmere',
]

export const STATE_NAMES: string[] = [
  // English / Anglo-Norman-ish
  'Northmarch',
  'Westmarch',
  'Eastmere',
  'Southvale',
  'Ashenford',
  'Greyshire',
  'Highwick',
  'Ravenmoor',
  'Stoneleigh',
  'Blackfen',

  // Germanic-ish
  'Eisenmark',
  'Hohenwald',
  'Dunkelheim',
  'Falkenmark',
  'Steinmark',
  'Grünwald',
  'Rosenfeld',
  'Adlergau',
  'Wintergau',
  'Lindenmark',

  // French-ish
  'Montclair',
  'Valbrune',
  'Beaufort',
  'Rocheval',
  'Aubemont',
  'Clairevaux',
  'Noirmont',
  'Vallombre',
  'Belrive',
  'Hauteroche',

  // Italian-ish
  'Valdoro',
  'Montefiore',
  'Castelverde',
  'Rivamara',
  'Bellacosta',
  'Roccalta',
  'Valserra',
  'Monteluce',
  'Fioravalle',
  'Terrabruna',

  // Low Countries / borderland-ish
  'Dornveld',
  'Bruggenland',
  'Meerveld',
  'Oosthaven',
  'Westerveld',
  'Zuidbroek',
  'Nieuwmark',
  'Rijnwold',
  'Bergdam',
  'Veldhaven',
]
