export const COUNTRY_NAMES: string[] = [
  'Aldoria',
  'Bergund',
  'Caldria',
  'Estenmark',
  'Lotharing',
  'Ravenna',
  'Valdric',
  'Westmere',
  'Dornheim',
  'Ferrath',
  'Greymark',
  'Hartfeld',
  'Ironwall',
  'Kelvara',
  'Lundbeck',
  'Morvaine',
  'Norwick',
  'Ostmark',
  'Pelstein',
  'Quelmar',
]

export const HOUSE_NAMES: string[] = [
  'House Arden',
  'House Falken',
  'House Montclair',
  'House Ravensburg',
  'House Valmont',
  'House Eisenwald',
  'House Hohenfels',
  'House Bellacourt',
  'House Crestfeld',
  'House Dunmore',
  'House Elderwick',
  'House Frostgate',
  'House Grimwald',
  'House Hartstone',
  'House Ironmoor',
  'House Kendrick',
  'House Larkspur',
  'House Merriwick',
  'House Nighthollow',
  'House Oswick',
]

export const PERSON_NAMES: string[] = [
  'Adalbert',
  'Alaric',
  'Baldwin',
  'Conrad',
  'Edmund',
  'Frederick',
  'Geoffrey',
  'Hugh',
  'Leopold',
  'Matthias',
  'Otto',
  'Raymond',
  'Roland',
  'Theobald',
  'William',
  'Heinrich',
  'Sigmund',
  'Gottfried',
  'Hartmann',
  'Dietrich',
  'Albrecht',
  'Berthold',
  'Clemens',
  'Ekkehard',
  'Gerhard',
  'Hildebrand',
  'Irmfried',
  'Johannes',
  'Klaus',
  'Lorenz',
]
